language: node_js
node_js:
  - 6
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 5.12.0
before_script:
  - npm install -g gulp-cli node-gyp
  - gem install sass
services: mongodb
cache:
  directories:
    - node_modules
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
